export enum NotificationType {
  NEW_EVALUATION_PERIOD = 'NEW_EVALUATION_PERIOD',
  EVALUATION_PERIOD_CLOSED = 'EVALUATION_PERIOD_CLOSED',
  EVALUATION_REJECTED = 'EVALUATION_REJECTED',
  GENERAL = 'GENERAL',
}
